services:
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      DATABASE_URL: postgres://ruahuwari:0595204077@webhook_pg:5432/webhook_db
    depends_on:
      - webhook_pg
  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
  webhook_pg:
    image: postgres:15
    environment:
      POSTGRES_USER: ruahuwari
      POSTGRES_PASSWORD: "0595204077"
      POSTGRES_DB: webhook_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: